force-app/main/default/objects/ETT_Job_Card__c/ETT_Job_Card__c.object-meta.xml
<CustomObject>
    <description>This is for the initial inspection stage to the final inspection stage.</description>
    <label>Job Card</label>
    <nameField>
        <displayFormat>JC-{0000}</displayFormat>
        <label>Job Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ETT_Job_Card__c/fields/ETT_Inspection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection Card</label>
    <referenceTo>ETT_Inspection_Card__c</referenceTo>
    <relationshipLabel>Job Cards</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/fields/Job_Card_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Card_Status__c</fullName>
    <label>Job Card Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close__c/ETT_Job_Card_Close__c.object-meta.xml
<CustomObject>
    <label>Job Card Close</label>
    <nameField>
        <displayFormat>JCC-{000000}</displayFormat>
        <label>Job Card Close Ref. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Card Close</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ETT_Job_Card_Close__c/fields/Job_Card__c.field-meta.xml
<CustomField>
    <fullName>Job_Card__c</fullName>
    <label>Job Card</label>
    <referenceTo>ETT_Job_Card__c</referenceTo>
    <relationshipLabel>Job Card Close</relationshipLabel>
    <relationshipName>Job_Card_Close</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <formula>Job_Card__r.ETT_Job_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close_Lines__c/ETT_Job_Card_Close_Lines__c.object-meta.xml
<CustomObject>
    <label>Job Card Close Lines</label>
    <nameField>
        <displayFormat>JCCL-{00000}</displayFormat>
        <label>Job Card Close Lines</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Card Close Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ETT_Job_Card_Close_Lines__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close_Lines__c/fields/Job_Card_Close__c.field-meta.xml
<CustomField>
    <fullName>Job_Card_Close__c</fullName>
    <label>Job Card Close</label>
    <referenceTo>ETT_Job_Card_Close__c</referenceTo>
    <relationshipLabel>Job Card Close Lines</relationshipLabel>
    <relationshipName>Job_Card_Close_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close_Lines__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETT_Job_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Line_Item__c/ETT_Job_Card_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Job Card Line Item</label>
    <nameField>
        <displayFormat>ACT-{00000}</displayFormat>
        <label>Job Card Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Card Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ETT_Job_Card_Line_Item__c/fields/ETT_Activity_Performed__c.field-meta.xml
<CustomField>
    <fullName>ETT_Activity_Performed__c</fullName>
    <label>Activity Performed</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETT_Retreading_Steps</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Line_Item__c/fields/ETT_Job_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Card__c</fullName>
    <label>Job Card</label>
    <referenceTo>ETT_Job_Card__c</referenceTo>
    <relationshipLabel>Job Card Line Items</relationshipLabel>
    <relationshipName>Job_Card_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Line_Item__c/fields/ETT_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Requisite Work</fullName>
            </value>
            <value>
                <fullName>Actual Work</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ETT_JobCardCloseCtrlTest.cls
@isTest
public class ETT_JobCardCloseCtrlTest {
    
    public static testmethod void jobcardClose(){
        
        List<Account> accountsList = ETT_TestFactory.createAccounts('TestAccountName', 'Tyre Customer');
        insert accountsList;
        
        Opportunity opp = ETT_TestFactory.createOpportunity('Tyre Supplier','TestOppName', 'Qualification', system.today().adddays(20), accountsList[0].Id);
        insert opp;
        
        
        List<ETT_Collection_Card__c> collectionCardsList = ETT_TestFactory.createCollectionCards(accountsList[0].Id,opp.Id);
        collectionCardsList[0].ETT_Inspection_Done__c = true;
        insert collectionCardsList;
          
        ETT_Job_Card__c jb = new ETT_Job_Card__c();
        jb.Job_Card_Status__c ='In Progress';
        insert jb;
        
        ETT_Job_Card_Close__c jc = new ETT_Job_Card_Close__c();
        jc.Status__c = 'New';
        jc.Job_Card__c=jb.Id;        
        insert jc;
        
        ETT_Job_Card_Close_Lines__c jcl = new ETT_Job_Card_Close_Lines__c();
        jcl.Available_Quantity__c =23;
        jcl.Job_Card_Close__c=jc.Id;
        insert jcl;
        
        List<ETT_Inspection_Card__c> inspectionList = new List<ETT_Inspection_Card__c>();
        ETT_Inspection_Card__c ic = new ETT_Inspection_Card__c();
        ic.ETT_Tyre_Serial_Number__c = '89383';
        ic.ETT_Collection_Card__c=collectionCardsList[0].Id;
        inspectionList.add(ic);
        insert inspectionList;
        
        WorkOrderLineItem wol  = new WorkOrderLineItem();
       
        
        ETT_Tools_Master__c  tool = new ETT_Tools_Master__c();
        tool.Name='Test';
        
        insert tool;
        
        ETT_Job_Card_Line_Item__c  jobCardLI = new ETT_Job_Card_Line_Item__c();
        jobCardLI.ETT_Job_Card__c = jb.id; 
        jobCardLI.ETT_Activity_Performed__c = 'Check Tube Flap and Envelop';
        jobCardLI.ETT_Type__c = 'Pause';
        jobCardLI.Sequence__c = 2;
        insert jobCardLI;
               
        ETT_JobCardCloseCtrl.getJobCardRealtedDetails(jb.Id);
        ETT_JobCardCloseCtrl.getselectOptions('ETT_Job_Card_Close_Lines__c','Job_Type__c');
        ETT_JobCardCloseCtrl.getBuffingInfo(jb.id);
        ETT_JobCardCloseCtrl.createJCcloseLinesUnderJC(new list<ETT_Job_Card_Close_Lines__c>{new ETT_Job_Card_Close_Lines__c()},jc.Id);
        ETT_JobCardCloseCtrl.getAllUsedItems(jb.Id);
        ETT_JobCardCloseCtrl.getToolMasterInfo(tool.Id);
        ETT_JobCardCloseCtrl.getCuringInfo(jb.Id);
        ETT_JobCardCloseCtrl.getEnvelopeInfo(jb.Id);
        //ETT_JobCardCloseCtrl.getJobTypeValue(inspectionList[0].id);
    }

}