force-app/main/default/objects/ETT_Job_Card__c/ETT_Job_Card__c.object-meta.xml
<CustomObject>
    <description>This is for the initial inspection stage to the final inspection stage.</description>
    <label>Job Card</label>
    <nameField>
        <displayFormat>JC-{0000}</displayFormat>
        <label>Job Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ETT_Job_Card__c/fields/Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Job Cards</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Cards</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/fields/ETT_Inspection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection Card</label>
    <referenceTo>ETT_Inspection_Card__c</referenceTo>
    <relationshipLabel>Job Cards</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/fields/ETT_Job_Stages_to_Perform_Ordered__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Stages_to_Perform_Ordered__c</fullName>
    <defaultValue>&quot;Buffing;Skiving;Repair;Cementing;Filling;Thread Preparation;Building;Rimming &amp; Enveloping;Curing;Removal of RIM Tube Flap;Final Inspection;Painting;Quality Control&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Job Stages to Perform (Ordered)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/fields/ETT_Main_Job_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Main_Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is only used in case of Thread preparation stage where the technician will be working in parallel with other station.</inlineHelpText>
    <label>Main Job Card</label>
    <referenceTo>ETT_Job_Card__c</referenceTo>
    <relationshipLabel>Job Cards</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/fields/ETT_No_of_Buffing_revisions__c.field-meta.xml
<CustomField>
    <fullName>ETT_No_of_Buffing_revisions__c</fullName>
    <label>No of Buffing revisions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/fields/ETT_Priority__c.field-meta.xml
<CustomField>
    <fullName>ETT_Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/fields/ETT_Stages__c.field-meta.xml
<CustomField>
    <fullName>ETT_Stages__c</fullName>
    <label>Current Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETT_Job_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/fields/Tyre_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Tyre_Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Inventory</label>
    <referenceTo>ETT_Tyre_Inventory__c</referenceTo>
    <relationshipLabel>Job Cards</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ETT_createJobCard.cls
/**
* Author:Janardhan
* CreatedDate: 16/12/2021
* Desc:
*testClass:ETT_createJobCardTest
* */
public class ETT_createJobCard {
    
    @auraEnabled
    public static user getUserDetails(){
        return [select id,name,Profile.Name from user where Id=:userinfo.getUserId()];
    }
    @auraEnabled
public static void createJobCard(String recordId, String actionVal) {
    Savepoint sp = Database.setSavepoint();
    List<ETT_Job_Card__c> listOfJobCards = new List<ETT_Job_Card__c>();
    Set<Id> tyreInventoryIds = new Set<Id>();

    try {
        ETT_Collection_Card__c cc = [SELECT ETT_Inspection_Done__c  FROM ETT_Collection_Card__c WHERE Id = :recordId LIMIT 1];

        if (!cc.ETT_Inspection_Done__c) {
            throw new AuraHandledException('Please do all inspections first.');
        }

        if (actionVal == 'Job Card Created') {
            List<ETT_Inspection_Card__c> lstInspectionCards = [
                SELECT Id, ETT_Account__c, ETT_Account__r.Name, RecordType.Name, Tyre_Inventory__c, ETT_Collection_Card__r.ETT_Priority__c, 
                       ETT_Collection_Card__c, ETT_Status__c, (SELECT Id FROM Job_Cards__r),(SELECT Id, Job_Type__c,SubInventory__c FROM Tyre_Inventory__r)
                FROM ETT_Inspection_Card__c 
                WHERE ETT_Status__c = 'Accept' 
                  AND ETT_Collection_Card__c = :recordId
            ];

            for (ETT_Inspection_Card__c objIC : lstInspectionCards) {
                if (objIC.Job_Cards__r.isEmpty()) {
                    ETT_Job_Card__c objJobCard = new ETT_Job_Card__c(
                        ETT_Inspection_Card__c = objIC.Id,
                        ETT_Job_Stages_to_Perform_Ordered__c = 'Buffing;Skiving;Repair;Cementing;Filling;Thread Preparation;Building;Rimming & Enveloping;Curing;Removal of RIM Tube Flap;Final Inspection;Painting;Quality Control',
                        Tyre_Inventory__c = objIC.Tyre_Inventory__c,
                        ETT_Stages__c = 'Buffing',
                        ETT_No_of_Buffing_revisions__c = 1,
                        ETT_Priority__c = objIC.ETT_Collection_Card__r.ETT_Priority__c,
                        Collection_Card__c = recordId,
                        Customer__c = objIC.ETT_Account__c,
                       
                        SubInventory__c=objIC.Tyre_Inventory__r.SubInventory__c

                    );

                    tyreInventoryIds.add(objIC.Tyre_Inventory__c);
                    listOfJobCards.add(objJobCard);
                }
            }

            if (!listOfJobCards.isEmpty()) {
                insert listOfJobCards;

                List<ETT_Tyre_Inventory__c> tyreList = [
                    SELECT Id, ETT_Inventory_Status__c 
                    FROM ETT_Tyre_Inventory__c 
                    WHERE Id IN :tyreInventoryIds
                ];

                for (ETT_Tyre_Inventory__c tyre : tyreList) {
                    tyre.ETT_Inventory_Status__c = 'Job Card Created';
                }
                update tyreList;

                cc.ETT_Job_Card_Done__c = true;
                cc.ETT_Collection_Status__c = 'Job Card Created';
            } else {
                throw new AuraHandledException('Please do all inspection cards first.');
            }
        } else if (actionVal == 'Check and Report') {
            cc.ETT_Collection_Status__c = actionVal;
        }

        update cc;
    } catch (Exception e) {
        System.debug('---ca' + e.getCause());
        System.debug('----Line' + e.getLineNumber());
        System.debug('---Trac-' + e.getStackTraceString());
        System.debug('---Type-' + e.getTypeName());
        System.debug('---err-' + e.getMessage());
        Database.rollback(sp);
        throw new AuraHandledException(e.getMessage());
    }
}

   
}