force-app/main/default/objects/ETT_JCC_Employee__c/ETT_JCC_Employee__c.object-meta.xml
<CustomObject>
    <label>JCC Employee</label>
    <nameField>
        <displayFormat>JCCE-{0000}</displayFormat>
        <label>JCC Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JCC Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ETT_JCC_Employee__c/fields/ETT_Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_Employee_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Employee Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ETT_JCC_Employee__c/fields/ETT_Job_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>ETT_Job_Card__c</referenceTo>
    <relationshipLabel>JCC Employees</relationshipLabel>
    <relationshipName>JCC_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ETT_JCC_Employee__c/fields/ETT_Job_Card_Close__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Card_Close__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card Close</label>
    <referenceTo>ETT_Job_Card_Close__c</referenceTo>
    <relationshipLabel>JCC Employees</relationshipLabel>
    <relationshipName>JCC_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ETT_JCC_Employee__c/fields/ETT_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETT_Job_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETT_JCC_Rejection_Analysis__c/ETT_JCC_Rejection_Analysis__c.object-meta.xml
<CustomObject>
    <label>JCC Rejection Analysis</label>
    <nameField>
        <displayFormat>JCCR-{0000}</displayFormat>
        <label>JCC Rejection Analysis Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JCC Rejection Analysises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ETT_JCC_Rejection_Analysis__c/fields/ETT_Job_Card_Close__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Card_Close__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card Close</label>
    <referenceTo>ETT_Job_Card_Close__c</referenceTo>
    <relationshipLabel>JCC Rejection Analysises</relationshipLabel>
    <relationshipName>JCC_Rejection_Analysises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/ETT_Job_Card__c.object-meta.xml
<CustomObject>
    <description>This is for the initial inspection stage to the final inspection stage.</description>
    <label>Job Card</label>
    <nameField>
        <displayFormat>JC-{0000}</displayFormat>
        <label>Job Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ETT_Job_Card__c/fields/ETT_Inspection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection Card</label>
    <referenceTo>ETT_Inspection_Card__c</referenceTo>
    <relationshipLabel>Job Cards</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/fields/ETT_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Type__c</fullName>
    <formula>ETT_Inspection_Card__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card__c/fields/Job_Card_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Card_Status__c</fullName>
    <label>Job Card Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close__c/ETT_Job_Card_Close__c.object-meta.xml
<CustomObject>
    <label>Job Card Close</label>
    <nameField>
        <displayFormat>JCC-{000000}</displayFormat>
        <label>Job Card Close Ref. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Card Close</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ETT_Job_Card_Close__c/fields/Job_Card__c.field-meta.xml
<CustomField>
    <fullName>Job_Card__c</fullName>
    <label>Job Card</label>
    <referenceTo>ETT_Job_Card__c</referenceTo>
    <relationshipLabel>Job Card Close</relationshipLabel>
    <relationshipName>Job_Card_Close</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <formula>Job_Card__r.ETT_Job_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close_Lines__c/ETT_Job_Card_Close_Lines__c.object-meta.xml
<CustomObject>
    <label>Job Card Close Lines</label>
    <nameField>
        <displayFormat>JCCL-{00000}</displayFormat>
        <label>Job Card Close Lines</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Card Close Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ETT_Job_Card_Close_Lines__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close_Lines__c/fields/ETT_Unique_Code__c.field-meta.xml
<CustomField>
    <fullName>ETT_Unique_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Item Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close_Lines__c/fields/Issued_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Issued_Quantity__c</fullName>
    <label>Issued Quantity</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close_Lines__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tools &amp; Material Name</description>
    <label>Item Name</label>
    <referenceTo>ETT_Tools_Master__c</referenceTo>
    <relationshipLabel>Job Card Close Lines</relationshipLabel>
    <relationshipName>Job_Card_Close_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close_Lines__c/fields/Job_Card_Close__c.field-meta.xml
<CustomField>
    <fullName>Job_Card_Close__c</fullName>
    <label>Job Card Close</label>
    <referenceTo>ETT_Job_Card_Close__c</referenceTo>
    <relationshipLabel>Job Card Close Lines</relationshipLabel>
    <relationshipName>Job_Card_Close_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Close_Lines__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETT_Job_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Line_Item__c/ETT_Job_Card_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Job Card Line Item</label>
    <nameField>
        <displayFormat>ACT-{00000}</displayFormat>
        <label>Job Card Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Card Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ETT_Job_Card_Line_Item__c/fields/ETT_Activity_Performed__c.field-meta.xml
<CustomField>
    <fullName>ETT_Activity_Performed__c</fullName>
    <label>Activity Performed</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETT_Retreading_Steps</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Line_Item__c/fields/ETT_Job_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Card__c</fullName>
    <label>Job Card</label>
    <referenceTo>ETT_Job_Card__c</referenceTo>
    <relationshipLabel>Job Card Line Items</relationshipLabel>
    <relationshipName>Job_Card_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ETT_Job_Card_Line_Item__c/fields/ETT_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Requisite Work</fullName>
            </value>
            <value>
                <fullName>Actual Work</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ETT_JobCardCloseCtrlNewTest.cls
@isTest
public class ETT_JobCardCloseCtrlNewTest {
    @isTest
static void jobcardCloseNew(){
   
    
        List<Account> accountsList = ETT_TestFactory.createAccounts('TestAccountName', 'Tyre Customer');
        insert accountsList;
        
        Opportunity opp = ETT_TestFactory.createOpportunity('Tyre Supplier','TestOppName', 'Qualification', system.today().adddays(20), accountsList[0].Id);
        insert opp;
        
        
        List<ETT_Collection_Card__c> collectionCardsList = ETT_TestFactory.createCollectionCards(accountsList[0].Id,opp.Id);
        collectionCardsList[0].ETT_Inspection_Done__c = true;
        insert collectionCardsList;
    
        List<ETT_Inspection_Card__c> inspectionList = new List<ETT_Inspection_Card__c>();
        ETT_Inspection_Card__c ic = new ETT_Inspection_Card__c();
        ic.ETT_Tyre_Serial_Number__c = '89383';
        ic.ETT_Collection_Card__c=collectionCardsList[0].Id;
        insert ic;
        inspectionList.add(ic);
        //insert inspectionList;
          
        ETT_Job_Card__c jb = new ETT_Job_Card__c();
        jb.Job_Card_Status__c ='In Progress';
        jb.ETT_Inspection_Card__c = ic.id;
        insert jb;
        
        ETT_Job_Card_Close__c jc = new ETT_Job_Card_Close__c();
        jc.Status__c = 'New';
        jc.Job_Card__c=jb.Id;        
        insert jc;
        
        ETT_Job_Card_Close_Lines__c jcl = new ETT_Job_Card_Close_Lines__c();
        jcl.Available_Quantity__c =23;
        jcl.Job_Card_Close__c=jc.Id;
        //jcl.ETT_Unique_Code__c = '113';
        insert jcl;
        List <ETT_Job_Card_Close_Lines__c> Jobcardcloseline = New List <ETT_Job_Card_Close_Lines__c>();
        Jobcardcloseline.add(jcl);
        
        /*List<ETT_Inspection_Card__c> inspectionList = new List<ETT_Inspection_Card__c>();
        ETT_Inspection_Card__c ic = new ETT_Inspection_Card__c();
        ic.ETT_Tyre_Serial_Number__c = '89383';
        ic.ETT_Collection_Card__c=collectionCardsList[0].Id;
        inspectionList.add(ic);
        insert inspectionList;*/
    
        
        //WorkOrderLineItem wol  = new WorkOrderLineItem();
       
        
        ETT_Tools_Master__c  tool = new ETT_Tools_Master__c();
        tool.Name='Test';
        
        insert tool;
        
        ETT_Job_Card_Line_Item__c  jobCardLI = new ETT_Job_Card_Line_Item__c();
        jobCardLI.ETT_Job_Card__c = jb.id; 
        jobCardLI.ETT_Activity_Performed__c = 'Check Tube Flap and Envelop';
        jobCardLI.ETT_Type__c = 'Pause';
        jobCardLI.Sequence__c = 2;
        insert jobCardLI;
   
        WorkOrder workord = New WorkOrder();
        workord.AccountId = accountsList[0].id;
        insert workord;
       WorkOrderLineItem Lineitem = New WorkOrderLineItem();
        Lineitem.ETT_Tyre_Serial_Number__c = ic.ETT_Tyre_Serial_Number__c;
        Lineitem.ETT_Collection_Card__c = ic.ETT_Collection_Card__c;
        Lineitem.ETT_Job_Type__c = 'Retread';
        Lineitem.WorkOrderId = workord.id;
        insert Lineitem;
    
        ETT_Tyre_Employee_Master__c ETemployee = New ETT_Tyre_Employee_Master__c();
        ETemployee.Employee_Name__c = 'Test';
        insert ETemployee;
    
        ETT_JCC_Employee__c JcEmployee = New ETT_JCC_Employee__c();
        JcEmployee.ETT_Employee_Name__c = 'Test';
        JcEmployee.ETT_Job_Card__c = jb.id;
        JcEmployee.ETT_Job_Card_Close__c = jc.id;
        insert JcEmployee;
    
        list<ETT_JCC_Employee__c> JcemployeeList = New list<ETT_JCC_Employee__c>();
        JcemployeeList.add(JcEmployee);
        
        ETT_JCC_Rejection_Analysis__c JcRejection = New ETT_JCC_Rejection_Analysis__c();
        JcRejection.ETT_Job_Card_Close__c = jc.id;
        insert JcRejection;
        
        ETT_Tyre_Rejection_Line_Item__c Tyrerejection = New ETT_Tyre_Rejection_Line_Item__c();
        Tyrerejection.Cut__c = 'Test12';
        //Tyrerejection.Crown_Cuts__c = 'test12';
        Tyrerejection.Name = 'SideWallArea';
        Tyrerejection.ETT_Inspection_Card__c = inspectionList[0].id;
        insert Tyrerejection;
        
               
        ETT_JobCardCloseCtrlNew.getJobCardRealtedDetails(jb.Id);
        ETT_JobCardCloseCtrlNew.getselectOptions('ETT_Job_Card_Close_Lines__c','Job_Type__c');
        ETT_JobCardCloseCtrlNew.getBuffingInfo(jb.id);
        //ETT_JobCardCloseCtrlNew.createJCcloseLinesUnderJC(new list<ETT_Job_Card_Close_Lines__c>{new ETT_Job_Card_Close_Lines__c()},jc.Id);
        ETT_JobCardCloseCtrlNew.getAllUsedItems(jb.Id);
        ETT_JobCardCloseCtrlNew.getToolMasterInfo(tool.Id);
        ETT_JobCardCloseCtrlNew.getCuringInfo(jb.Id);
        ETT_JobCardCloseCtrlNew.getEnvelopeInfo(jb.Id);
        ETT_JobCardCloseCtrlNew.getJobTypeValue(ic.id);
        ETT_JobCardCloseCtrlNew.getAllEmployees(jb.id);
        ETT_JobCardCloseCtrlNew.getTyreEmployeeMasterInfo(ETemployee.id);
    try{
        ETT_JobCardCloseCtrlNew.createJCcloseLinesUnderJC(Jobcardcloseline, jc.Id, JcemployeeList, JcRejection, jb);
    }catch(Exception e){}
    }
     @isTest
static void jobcardCloseNew2(){
        
        List<Account> accountsList = ETT_TestFactory.createAccounts('TestAccountName', 'Tyre Customer');
        insert accountsList;
        
        Opportunity opp = ETT_TestFactory.createOpportunity('Tyre Supplier','TestOppName', 'Qualification', system.today().adddays(20), accountsList[0].Id);
        insert opp;
        
        
        List<ETT_Collection_Card__c> collectionCardsList = ETT_TestFactory.createCollectionCards(accountsList[0].Id,opp.Id);
        collectionCardsList[0].ETT_Inspection_Done__c = true;
        insert collectionCardsList;
    
        List<ETT_Inspection_Card__c> inspectionList = new List<ETT_Inspection_Card__c>();
        ETT_Inspection_Card__c ic = new ETT_Inspection_Card__c();
        ic.ETT_Tyre_Serial_Number__c = '89383';
        ic.ETT_Collection_Card__c=collectionCardsList[0].Id;
        insert ic;
        inspectionList.add(ic);
        //insert inspectionList;
          
        ETT_Job_Card__c jb = new ETT_Job_Card__c();
        jb.Job_Card_Status__c ='In Progress';
        jb.ETT_Inspection_Card__c = ic.id;
        insert jb;
        
        ETT_Job_Card_Close__c jc = new ETT_Job_Card_Close__c();
        jc.Status__c = 'New';
        jc.Job_Card__c=jb.Id;        
        insert jc;
    
       ETT_Tools_Master__c toolmaster = New ETT_Tools_Master__c();
        toolmaster.Name = 'Test';
        toolmaster.ETT_Main_Stock_Units__c = 2;
        insert toolmaster;
        
        ETT_Job_Card_Close_Lines__c jcl = new ETT_Job_Card_Close_Lines__c();
        jcl.Available_Quantity__c =23;
        jcl.Job_Card_Close__c=jc.Id;
        jcl.ETT_Unique_Code__c = '113';
        jcl.Item_Name__c = toolmaster.id;
        jcl.Issued_Quantity__c = null;
        insert jcl;
        List <ETT_Job_Card_Close_Lines__c> Jobcardcloseline = New List <ETT_Job_Card_Close_Lines__c>();
        Jobcardcloseline.add(jcl);
    
        
        /*List<ETT_Inspection_Card__c> inspectionList = new List<ETT_Inspection_Card__c>();
        ETT_Inspection_Card__c ic = new ETT_Inspection_Card__c();
        ic.ETT_Tyre_Serial_Number__c = '89383';
        ic.ETT_Collection_Card__c=collectionCardsList[0].Id;
        inspectionList.add(ic);
        insert inspectionList;*/
    
        
        //WorkOrderLineItem wol  = new WorkOrderLineItem();
       
        
        
        /*WorkOrderLineItem Lineitem = New WorkOrderLineItem();
        Lineitem.ETT_Tyre_Serial_Number__c = ic.ETT_Tyre_Serial_Number__c;
        Lineitem.ETT_Collection_Card__c = ic.ETT_Collection_Card__c;
        Lineitem.ETT_Job_Type__c = 'Retread';
        insert Lineitem;*/
    
        ETT_JCC_Employee__c JcEmployee = New ETT_JCC_Employee__c();
        JcEmployee.ETT_Employee_Name__c = 'Test';
        JcEmployee.ETT_Job_Card__c = jb.id;
        JcEmployee.ETT_Job_Card_Close__c = jc.id;
        insert JcEmployee;
    
        list<ETT_JCC_Employee__c> JcemployeeList = New list<ETT_JCC_Employee__c>();
        JcemployeeList.add(JcEmployee);
        
        ETT_JCC_Rejection_Analysis__c JcRejection = New ETT_JCC_Rejection_Analysis__c();
        JcRejection.ETT_Job_Card_Close__c = jc.id;
        insert JcRejection;
        
        ETT_Tyre_Rejection_Line_Item__c Tyrerejection = New ETT_Tyre_Rejection_Line_Item__c();
        Tyrerejection.Cut__c = 'Test12';
        //Tyrerejection.Crown_Cuts__c = 'test12';
        Tyrerejection.Name = 'SideWallArea';
        Tyrerejection.ETT_Inspection_Card__c = inspectionList[0].id;
        insert Tyrerejection;
        
               
        ETT_JobCardCloseCtrlNew.getJobCardRealtedDetails(jb.Id);
        ETT_JobCardCloseCtrlNew.getselectOptions('ETT_Job_Card_Close_Lines__c','Job_Type__c');
        ETT_JobCardCloseCtrlNew.getBuffingInfo(jb.id);
        //ETT_JobCardCloseCtrlNew.createJCcloseLinesUnderJC(new list<ETT_Job_Card_Close_Lines__c>{new ETT_Job_Card_Close_Lines__c()},jc.Id);
        ETT_JobCardCloseCtrlNew.getAllUsedItems(jb.Id);
        ETT_JobCardCloseCtrlNew.getToolMasterInfo(toolmaster.Id);
        ETT_JobCardCloseCtrlNew.getCuringInfo(jb.Id);
        ETT_JobCardCloseCtrlNew.getEnvelopeInfo(jb.Id);
        //ETT_JobCardCloseCtrlNew.getJobTypeValue(ic.id);
        ETT_JobCardCloseCtrlNew.getAllEmployees(jb.id);
    try{
        ETT_JobCardCloseCtrlNew.createJCcloseLinesUnderJC(Jobcardcloseline, jc.Id, JcemployeeList, JcRejection, jb);
    }catch(Exception e){}
    }
    /*@isTest
    static void jobcardCloseNew1(){
        
        List<Account> accountsList = ETT_TestFactory.createAccounts('TestAccountName', 'Tyre Customer');
        insert accountsList;
        
        Opportunity opp = ETT_TestFactory.createOpportunity('Tyre Supplier','TestOppName', 'Qualification', system.today().adddays(20), accountsList[0].Id);
        insert opp;
        
        
        List<ETT_Collection_Card__c> collectionCardsList = ETT_TestFactory.createCollectionCards(accountsList[0].Id,opp.Id);
        collectionCardsList[0].ETT_Inspection_Done__c = true;
        insert collectionCardsList;
    
        List<ETT_Inspection_Card__c> inspectionList = new List<ETT_Inspection_Card__c>();
        ETT_Inspection_Card__c ic = new ETT_Inspection_Card__c();
        ic.ETT_Tyre_Serial_Number__c = '89383';
        ic.ETT_Collection_Card__c=collectionCardsList[0].Id;
        inspectionList.add(ic);
        insert inspectionList;
          
        ETT_Job_Card__c jb = new ETT_Job_Card__c();
        jb.Job_Card_Status__c ='In Progress';
        insert jb;
        
        ETT_Job_Card_Close__c jc = new ETT_Job_Card_Close__c();
        jc.Status__c = 'New';
        jc.Job_Card__c=jb.Id;        
        insert jc;
        
        ETT_Tools_Master__c toolmaster = New ETT_Tools_Master__c();
        toolmaster.Name = 'Test';
        toolmaster.ETT_Main_Stock_Units__c = 2;
        insert toolmaster;
        
        ETT_Job_Card_Close_Lines__c jcl = new ETT_Job_Card_Close_Lines__c();
        jcl.Available_Quantity__c =23;
        jcl.Job_Card_Close__c=jc.Id;
        jcl.ETT_Unique_Code__c = '113';
        jcl.Item_Name__c = toolmaster.id;
        jcl.Issued_Quantity__c = null;
        insert jcl;
        
        List <ETT_Job_Card_Close_Lines__c> Jobcardcloseline = New List <ETT_Job_Card_Close_Lines__c>();
        Jobcardcloseline.add(jcl);
        
        /*List<ETT_Inspection_Card__c> inspectionList = new List<ETT_Inspection_Card__c>();
        ETT_Inspection_Card__c ic = new ETT_Inspection_Card__c();
        ic.ETT_Tyre_Serial_Number__c = '89383';
        ic.ETT_Collection_Card__c=collectionCardsList[0].Id;
        inspectionList.add(ic);
        insert inspectionList;*/
    
        
        /*WorkOrderLineItem wol  = new WorkOrderLineItem();
       
        
        ETT_Tools_Master__c  tool = new ETT_Tools_Master__c();
        tool.Name='Test';
        
        insert tool;
        
        ETT_Job_Card_Line_Item__c  jobCardLI = new ETT_Job_Card_Line_Item__c();
        jobCardLI.ETT_Job_Card__c = jb.id; 
        jobCardLI.ETT_Activity_Performed__c = 'Check Tube Flap and Envelop';
        jobCardLI.ETT_Type__c = 'Pause';
        jobCardLI.Sequence__c = 2;
        insert jobCardLI;
    
        /*WorkOrderLineItem Lineitem = New WorkOrderLineItem();
        Id devRecordTypeId = Schema.SObjectType.WorkOrderLineItem.getRecordTypeInfosByName().get('Tyre - Cash Supplier').getRecordTypeId();
        Lineitem.RecordTypeId = devRecordTypeId;
        Lineitem.ETT_Tyre_Serial_Number__c = inspectionList[0].ETT_Tyre_Serial_Number__c;
        Lineitem.ETT_Collection_Card__c = collectionCardsList[0].Id;
        Lineitem.ETT_Job_Type__c = 'Retread';
        insert Lineitem;*/
        
       /* ETT_JCC_Employee__c JcEmployee = New ETT_JCC_Employee__c();
        JcEmployee.ETT_Employee_Name__c = 'Test';
        JcEmployee.ETT_Job_Card__c = jb.id;
        JcEmployee.ETT_Job_Card_Close__c = jc.id;
        insert JcEmployee;
    
        list<ETT_JCC_Employee__c> JcemployeeList = New list<ETT_JCC_Employee__c>();
        JcemployeeList.add(JcEmployee);
        
        ETT_JCC_Rejection_Analysis__c JcRejection = New ETT_JCC_Rejection_Analysis__c();
        JcRejection.ETT_Job_Card_Close__c = jc.id;
        insert JcRejection;
        
        ETT_Tyre_Rejection_Line_Item__c Tyrerejection = New ETT_Tyre_Rejection_Line_Item__c();
        Tyrerejection.Cut__c = 'Test12';
        //Tyrerejection.Crown_Cuts__c = 'test12';
        Tyrerejection.Name = 'CrownArea';
        Tyrerejection.ETT_Inspection_Card__c = inspectionList[0].id;
        insert Tyrerejection;
        
        
    try{
        ETT_JobCardCloseCtrlNew.createJCcloseLinesUnderJC(Jobcardcloseline, jc.Id, JcemployeeList, JcRejection, jb);
    }catch(Exception e){}
    }*/

}